### ISSUE TITLE
feat: global configuration system

### ISSUE THREAD

**Issue by Krzyhau** [FEZModding/HAT#10]
These informations should be save somewhere in a common file for HAT to determine how to handle mods:
- enabled state of the mod (whether the mod should load or not)
- mod version to load (by default, loads the newest one)
- custom ordering of mods (a secondary, after dependency priority, user-based ordering for resolving asset conflicts)

**Comment by Jenna1337** [comment]
Related: #3

**Comment by Krzyhau** [comment]
I've implemented a very basic solution that should be sufficient enough: `blacklist.txt` (16c45eb) and `prioritylist.txt` (f33d767) files within the `Mods` directory, in which you can list files to disable and prioritize during mod loading process.

More advanced configuration should be implemented in an individual mod configuration system, for which I've created a separate issue: #18

As for this issue, I'm considering it done.

**Comment by Jenna1337** [comment]
I heard the term "blacklist" is a term that should be avoided because it could be considered racist or something. Consider changing it to "blocklist" or "ignorelist" or similar

**Comment by Krzyhau** [comment]
The term "blacklist" does not refer to human race in any way. However, I might change it to `ignorelist` just because it sounds better when paired with `prioritylist`.

On an unrelated note:
![image](https://github.com/FEZModding/HAT/assets/16310330/a73844eb-7a66-41fe-9374-40993963fc8d)
