### ISSUE TITLE
bug: switching save slots crashes HAT 

### ISSUE THREAD

**Issue by Jenna1337** [FEZModding/HAT#5]
Tested on release v1.0.2

Steps to reproduce:
1. open HAT modded FEZ
2. load a save slot
3. go to "help & options" > "save management" > "change slot"
4. select a different slot
5. press enter to advance past the "HAT" logo

![image](https://user-images.githubusercontent.com/11368561/215347509-03ca13ef-4cf9-45ee-8e9b-6dd54d04f08c.png)

**Comment by Krzyhau** [comment]
This issue has already been solved by e5f2ee0 and will be delivered on the next release. Closing.
